### ISSUE TITLE
Repo 命名规则

### ISSUE THREAD

**Issue by realfish** [cnpolitics/editor-quiz#1]
- 仅由小写拉丁字母、数字和 hyphen (-) 构成。
- 不以「cnpolitics」开头
- 命名有实义性，例如「eic-exam」「official-promotion」。

**Comment by ghost** [comment]
已遵照规则修改repo名

**Comment by realfish** [comment]
名称也换个吧，体现一下游戏内容。我之前传的两个「demo」来自别的团队；因为我们这里没有 private repo 的额度，所以我故意起了无意义的名字，权当起一些隐藏作用 : p
